name: Release Drafter

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write  # to create/update the draft release
    steps:
      - uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
