name: Release Drafter

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write  # to create/update the draft release
    steps:
      - uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
